site_name: Pydantic Factories
repo_url: https://github.com/starlite-api/pydantic-factories
repo_name: starlite-api/pydantic-factories
site_url: https://starlite-api.github.io/pydantic-factories
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search:
        lang: en
    - social:
        cards_color:
          fill: "#1d2433"
          text: "#d6dbe1"
        cards_font: Tahoma

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search:
      lang: en
